version: '3'

services:

  mongo_desafio_dev:
    image: mongo
    container_name: mongo_desafio_dev
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./data:/data/db

  node:
    build: .
    container_name: mongo_desafio_dev
    # restart: always
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - mongo_desafio_dev
    volumes:
      - .:/app
      - /app/node_modules