version: '3'

services:

  mongo_desafio:
    image: mongo
    container_name: mongo_desafio
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./data:/data/db

  node:
    build: .
    container_name: node_desafio
    # restart: always
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - mongo_desafio
    volumes:
      - .:/app
      - /app/node_modules